name: money_calc_app
description: "KASA+ Money Counter Application"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  file_picker: ^10.3.7
  fl_chart: 0.68.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  provider: ^6.1.2
  share_plus: ^12.0.1
  shared_preferences: ^2.5.3
  tutorial_coach_mark: ^1.3.3

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true
  generate: true
